### ISSUE TITLE
Can we add this to http://UKHomeOffice.github.io ?

### ISSUE THREAD

**Issue by PurpleBooth** [UKHomeOffice/io-it#2]
https://github.com/UKHomeOffice/UKHomeOffice.github.io

**Comment by davidainslie** [comment]
Yes

**Comment by PurpleBooth** [comment]
Added. Thanks!

If you can think of anything else that should be added there, just submit a pr

**Comment by davidainslie** [comment]
Thought I'd let you know of 2 other useful projects we opened sourced at the same time as rtp-io-lib.
They are:

https://github.com/UKHomeOffice/rtp-akka-lib
and
https://github.com/UKHomeOffice/rtp-rabbit-lib

**Comment by PurpleBooth** [comment]
I got them as well, thanks!
